### PR TITLE
fix #18

### LINKED ISSUE #18: cppcheck seems to work but no lint results appear
I get the same question described [here](https://stackoverflow.com/questions/50984107/cppcheck-seems-to-work-but-no-lint-results-appear-subilme-text-3-mac).
In short, in sublime console, cppcheck works just fine. However, when running `SublimeLinter: Show all errors` command in `ctrl + shift + p`, it shows `No lint results.` 

I'm using win7 & sublime text  3 build 3143 & SublimeLinter v4.6.6 & SublimeLinter-cppcheck v1.1.1.

### PR DESCRIPTION
**Pull request by irvingzhang0512**
not sure when this issue came out and what caused this.
plz make sure this PR works for everyone.

### CODE REVIEW

**Comment by kaste** [comment]
I edited my first comment bc GitHub removed the named tags. Make sure to look at it online!

What comes to my mind: I think we can also mangle --template so that we get a consistent report on every system.

**Comment by irvingzhang0512** [comment]
Hi kaste, thank you for your advice, it's very helpful.
However, when i follow your advice, using `r'^(?P<file>.+):(?P<line>\d+):((?P<col>\d+):)?\s+'` instead, i cannot get correct `line` & `col` from errormsg(`test.txt:1:12: `). 
The result of `re.compile(regex).math(errormsg)` is `{'file': 'test.txt:1 ', 'line': '1', 'col': None}`.

Here is my first solution. Let's assume every `file` has a extension, which means every `file` string has a char `.`
so the regex is `r'^(?P<file>.+\.[^:]+):(?P<line>\d+):((?P<col>\d+):)?\s+'`, which works fine for both `test.txt:1:12: ` & `test.txt:1: `
Obviously, this solution has a limitation: the `file` string must have a char `.`

Sorry about my poor english, but i don't get you about:

>  I think we can also mangle --template so that we get a consistent report on every system.

Maybe you mean we can set different regex for different os?
Which lead to my second solution: we can get current os information by python (eg. `platform.system()`) and choose regex correspondingly.

**Comment by kaste** [comment]
I hate regexes.

Okay, you can try `(?P<file>(:\\|[^:])+):(?P<line>\d+):((?P<col>\d+):)?\s+`, here a filename consumes every char that is not a `:` unless it is a `:\` (bc `D:\foo\bar`)

That regex also has the benefit that it looks like I wrote a smiley.

**Comment by kaste** [comment]
Ah, the `--template` is a special arg to cppcheck where we can define the output format cppcheck produces.

**Comment by irvingzhang0512** [comment]
it works! thank you very much.

PS: i have regexes, too...
PPS: i'm not familiar with cppcheck, but i agree with you,  setting cppcheck template is a better solution.

**Comment by kaste** [comment]
🎉

**Comment by kaste** [comment]
Released https://github.com/SublimeLinter/SublimeLinter-cppcheck/releases/tag/1.1.2

**Pull request merged**
